Deface::Override.new :virtual_path  => 'users/_form',
                     :name          => 'add-admin-superuser-form',
                     :original		=> 'e60a4fa50dfadff1543026068000af0103515325',
                     :replace		=> "erb[loud]:contains('admin')",
                     #:insert_before	=> "erb[loud]:contains('view_users_form,')",
                     #:text			=> 'holaaaaaaaaaaaaa'
                     #:partial       => 'users/superuser_form'
                     #:partial       => 'users/user_form_superuser_2'
                     :partial       => 'users/user_form_superuser'
